- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927
    state: present
  tags: install

- name: Add APT repository    
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    filename: /etc/apt/sources.list.d/mongodb-org-3.2.list
    update_cache: yes
    state: present
  tags: install  


- name: Install the package "mongodb-org"
  apt:
    name: mongodb-org
    force: yes
    state: present
  tags: install  

- name: enable/start mongod
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
  